import { getDatabase } from '@/core/data/database/client';
import { AppTelemetry } from '@/core/observability/app-telemetry';

/**
 * Recurrence interval with multiplier support.
 * Format: `{count}{unit}` e.g. "1D", "2W", "3M", "1Y", "6H"
 * Also supports legacy plain units: "HOURLY", "DAILY", "WEEKLY", "MONTHLY"
 */
function parseInterval(raw: string): { count: number; unit: 'h' | 'd' | 'w' | 'm' | 'y' } {
  const normalized = raw.trim().toUpperCase();

  // Legacy format
  const legacyMap: Record<string, { count: number; unit: 'h' | 'd' | 'w' | 'm' | 'y' }> = {
    'HOURLY': { count: 1, unit: 'h' },
    'DAILY': { count: 1, unit: 'd' },
    'WEEKLY': { count: 1, unit: 'w' },
    'MONTHLY': { count: 1, unit: 'm' },
    'YEARLY': { count: 1, unit: 'y' },
  };
  if (legacyMap[normalized]) return legacyMap[normalized];

  // Compact format: "2W", "3M", etc.
  const match = normalized.match(/^(\d+)([HDWMY])$/);
  if (match) {
    const count = parseInt(match[1], 10);
    const unitMap: Record<string, 'h' | 'd' | 'w' | 'm' | 'y'> = { H: 'h', D: 'd', W: 'w', M: 'm', Y: 'y' };
    return { count, unit: unitMap[match[2]] ?? 'd' };
  }

  // Fallback
  return { count: 1, unit: 'd' };
}

function nextRunFromInterval(current: number, intervalRaw: string) {
  const { count, unit } = parseInterval(intervalRaw);
  const date = new Date(current);

  switch (unit) {
    case 'h':
      date.setHours(date.getHours() + count);
      break;
    case 'd':
      date.setDate(date.getDate() + count);
      break;
    case 'w':
      date.setDate(date.getDate() + count * 7);
      break;
    case 'm':
      date.setMonth(date.getMonth() + count);
      break;
    case 'y':
      date.setFullYear(date.getFullYear() + count);
      break;
  }

  return date.getTime();
}

export async function executeDueRecurringRules(userId: string) {
  const db = await getDatabase();
  const now = Date.now();
  const rows = await db.getAllAsync<{
    id: string;
    label: string;
    kind: string;
    interval: string;
    next_run_at: number;
    amount: number | null;
  }>('SELECT id,label,kind,interval,next_run_at,amount FROM recurring_rules WHERE user_id = ? AND active = 1 AND next_run_at <= ?', userId, now);

  if (!rows.length) return 0;

  let processed = 0;
  await db.withTransactionAsync(async () => {
    for (const rule of rows) {
      const createdAt = new Date().toISOString();
      AppTelemetry.trackEvent('recurring_rule_executed', {
        rule_id: rule.id,
        kind: rule.kind,
        interval: rule.interval,
      });
      if (rule.kind === 'TASK') {
        await db.runAsync(
          `INSERT INTO tasks (
            user_id,id,title,description,priority,deadline,status,completed_at,reminder_offsets,alarm_enabled,
            created_at,updated_at,sync_state,record_source,revision,deleted_at
          ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
          userId,
          `task_recurring_${Date.now()}_${Math.round(Math.random() * 10000)}`,
          rule.label,
          'Generated by recurring rule',
          'MEDIUM',
          now + 24 * 60 * 60 * 1000,
          'PENDING',
          null,
          '15,60',
          1,
          createdAt,
          createdAt,
          'QUEUED',
          'RECURRING',
          1,
          null,
        );
      } else if (rule.kind === 'INCOME') {
        await db.runAsync(
          `INSERT INTO incomes (
            user_id,id,source,amount,date,note,created_at,updated_at,sync_state,record_source,revision,deleted_at
          ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,
          userId,
          `income_recurring_${Date.now()}_${Math.round(Math.random() * 10000)}`,
          rule.label,
          rule.amount ?? 0,
          now,
          'Generated by recurring rule',
          createdAt,
          createdAt,
          'QUEUED',
          'RECURRING',
          1,
          null,
        );
      } else {
        await db.runAsync(
          `INSERT INTO transactions (
            user_id,id,amount,merchant,category,date,source,transaction_type,mpesa_code,source_hash,semantic_hash,raw_sms,
            inferred_category,inference_source,created_at,updated_at,sync_state,record_source,revision,deleted_at
          ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
          userId,
          `tx_recurring_${Date.now()}_${Math.round(Math.random() * 10000)}`,
          rule.amount ?? 0,
          rule.label,
          'Other',
          now,
          'Manual',
          'PAID',
          null,
          null,
          null,
          null,
          null,
          null,
          createdAt,
          createdAt,
          'QUEUED',
          'RECURRING',
          1,
          null,
        );
      }

      const nextRun = nextRunFromInterval(rule.next_run_at, rule.interval);
      await db.runAsync(
        'UPDATE recurring_rules SET next_run_at = ?, updated_at = ?, sync_state = ? WHERE user_id = ? AND id = ?',
        nextRun,
        createdAt,
        'QUEUED',
        userId,
        rule.id,
      );

      processed += 1;
    }
  });

  return processed;
}