export const KNOWN_MERCHANTS: Record<string, string> = {
  // ── Food & Dining (22) ──
  'kfc': 'Food',
  'java': 'Food',
  'artcaffe': 'Food',
  'big square': 'Food',
  'cafe deli': 'Food',
  'chicken inn': 'Food',
  'chicken licken': 'Food',
  'pizza inn': 'Food',
  'dominos': 'Food',
  'subway': 'Food',
  'mcdonalds': 'Food',
  'macdonalds': 'Food',
  'steers': 'Food',
  'kennis': 'Food',
  'artisan coffee': 'Food',
  'costa': 'Food',
  'starbucks': 'Food',
  'wimpy': 'Food',
  'burger king': 'Food',
  'galitos': 'Food',
  'habesha': 'Food',
  'roast house': 'Food',

  // ── Groceries (11) ──
  'naivas': 'Groceries',
  'quickmart': 'Groceries',
  'cleanshelf': 'Groceries',
  'tuskys': 'Groceries',
  'chandarana': 'Groceries',
  'uchumi': 'Groceries',
  'jamii supermarket': 'Groceries',
  'eastmatt': 'Groceries',
  'freshmat': 'Groceries',
  'carrefour': 'Groceries',

  // ── Shopping (12) ──
  'mattress': 'Shopping',
  'jumia': 'Shopping',
  'kilimall': 'Shopping',
  'masoko': 'Shopping',
  'glovo': 'Shopping',
  'copa': 'Shopping',
  'amazon': 'Shopping',
  'aliexpress': 'Shopping',
  'shein': 'Shopping',
  'temu': 'Shopping',
  'wholesale': 'Shopping',
  'bata': 'Shopping',

  // ── Transport (20) ──
  'uber': 'Transport',
  'bolt': 'Transport',
  'little': 'Transport',
  'swvl': 'Transport',
  'kenya railways': 'Transport',
  'sgr': 'Transport',
  'total': 'Transport',
  'shell': 'Transport',
  'galana': 'Transport',
  'rubis': 'Transport',
  'national oil': 'Transport',
  'ivo': 'Transport',
  'gulf': 'Transport',
  'stabex': 'Transport',
  'oilibya': 'Transport',
  'engen': 'Transport',
  'pro energy': 'Transport',
  'hashi': 'Transport',
  'ridyn': 'Transport',
  'hive': 'Transport',

  // ── Bills (16) ──
  'kplc': 'Bills',
  'kenya power': 'Bills',
  'safaricom': 'Bills',
  'airtel': 'Bills',
  'telkom': 'Bills',
  'zuku': 'Bills',
  'water': 'Bills',
  'nairobi water': 'Bills',
  'electricity': 'Bills',
  'dstv': 'Bills',
  'gotv': 'Bills',
  'startimes': 'Bills',
  'kra': 'Bills',
  'nssf': 'Bills',
  'huduma': 'Bills',
  'paybill': 'Bills',

  // ── Subscriptions (6) ──
  'netflix': 'Subscriptions',
  'spotify': 'Subscriptions',
  'youtube': 'Subscriptions',
  'showmax': 'Subscriptions',
  'apple': 'Subscriptions',
  'deezer': 'Subscriptions',

  // ── Entertainment (4) ──
  'imax': 'Entertainment',
  'anga': 'Entertainment',
  'century cinemax': 'Entertainment',
  'cinemax': 'Entertainment',

  // ── Health (6) ──
  'nhif': 'Health',
  'pharmacy': 'Health',
  'hospital': 'Health',
  'clinic': 'Health',
  'doctor': 'Health',
  'medical': 'Health',

  // ── Education (5) ──
  'school': 'Education',
  'university': 'Education',
  'college': 'Education',
  'exam': 'Education',
  'tuition': 'Education',

  // ── Business & Finance (6) ──
  'm-shwari': 'Loans & Credit',
  'kcb m-pesa': 'Loans & Credit',
  'pochi': 'Business',
  'kopo kopo': 'Business',
  'lipa na m-pesa': 'Business',
  'till number': 'Business',

  // ── Savings (3) ──
  'savings': 'Savings',
  'deposit': 'Deposit',
  'atm': 'Withdrawal',
};